// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int32              `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Features      []byte             `json:"features"`
	Active        *bool              `json:"active"`
	EmailVerified *bool              `json:"email_verified"`
	LastLogin     pgtype.Timestamptz `json:"last_login"`
	CreatedBy     *int32             `json:"created_by"`
	UpdatedBy     *int32             `json:"updated_by"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
