name: Format Go Code

on:
  workflow_dispatch:

jobs:
  go-fmt:
    name: Auto-format Go Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache-dependency-path: './backend/go.sum'

      - name: Run gofmt
        working-directory: ./backend
        run: |
          gofmt -w .

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatted code
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add backend/
          git commit -m "style: auto-format Go code with gofmt"
          git push
